// capturar o h1

const h1= document.querySelector("h1");

const a= document.querySelector("a");

const ul=document.querySelector("ul");

const ol=document.querySelector("ol");


let elementoH1 = document.querySelector("h1");
console.log(elementoH1);
console.log(elementoH1.innerText);

let elementool = document.querySelector("ol");
console.log(elementool);
console.log(elementool.innerText);

let elementoa = document.querySelector("a");
console.log(elementoa);
console.log(elementoa.innerText);

let elementoul = document.querySelector("ul");
console.log(elementoul);
console.log(elementoul.innerhtml);

l